# Generated by Django 3.0.7 on 2020-06-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20200606_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AlterField(
            model_name='result',
            name='file_result_result',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='CalculatePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=200)),
                ('file_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.File')),
            ],
        ),
    ]
